### ISSUE TITLE
Ensure unused-deps check is being run

### ISSUE THREAD

**Issue by jmsfltchr** [typedb/typedb-benchmark#79]

**Comment by haikalpribadi** [comment]
This is not something that warrants an issue, @jmsfltchr . You can just run one line of a command, and fix it immediately on the spot, which would take you less time than writing this one-liner issue. This is the command, which you can find in every automation.yml:
```
bazel run @graknlabs_dependencies//tool/unuseddeps:unused-deps -- list
```
