### ISSUE TITLE
Refactor package structure top-down

### ISSUE THREAD

**Issue by jmsfltchr** [typedb/typedb-benchmark#83]
## Description

There are clear issue with the current package structure.

For example
- `common`, `neo4j` and `grakn` should be top-level packages. 
- `test` contains `test-comparison` which should be obvious from the package and/or class naming

**Comment by haikalpribadi** [comment]
I seem to see that the package structure is already the way you describe it in this issue, so I'll be closing this issue. Please don't forget about issues you create when you're working @jmsfltchr, and update them regularly. We don't want a backlog of irrelevant and outdated issues.
