### ISSUE TITLE
Rename TransactionAgent to PurchaseAgent

### ISSUE THREAD

**Issue by jmsfltchr** [typedb/typedb-benchmark#89]
## Description

`TransactionAgent` is a confusing name in a benchmark of databases which deal in transactions. Really we are modelling customer purchases, so this should be changed to `PurchaseAgent`.

**Comment by haikalpribadi** [comment]
Done https://github.com/graknlabs/benchmark/commit/398f1775b961d6c19d1f9ebf24138ce174ace668
